name: slang_cli
description: CLI for slang, a type-safe i18n library for Dart and Flutter.
version: 4.12.1
repository: https://codeberg.org/Tienisto/slang
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

executables:
  slang: slang_cli

dependencies:
  analyzer: '>=6.0.0'
  collection: ^1.15.0
  file: ^7.0.0
  glob: ^2.0.0
  path: ^1.8.0
  slang:
    path: ../slang
  watcher: ^1.0.2
  yaml: ^3.1.0

dev_dependencies:
  lints: any
  test: ^1.21.0
