name: slang
description: Type-safe i18n for Dart and Flutter.
version: 4.12.1
repository: https://codeberg.org/Tienisto/slang
homepage: https://pub.dev/packages/slang

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.15.0
  csv: ">=5.0.1 <7.0.0"
  intl: ">=0.18.1 <2.0.0"
  yaml: ^3.1.0

dev_dependencies:
  analyzer: ">=6.0.0"
  lints: any
  test: ^1.21.0
